# Giao diện và giao diện người dùng
minimal_mistakes_skin    : "dark"  # Chọn chủ đề giao diện tối

# Cài đặt trang web
locale                   : "en-US"  # Ngôn ngữ của trang web
title                    : "Nho Tin | Personal Blog"  # Tiêu đề trang web
subtitle                 : "My Personal Blog"  # Phụ đề
name                     : "Lê Tô Nho Tín"  # Tên tác giả
description              : "Blog about Knowledge sharing in programming and My personal life as a programmer"  # Mô tả trang web
url                      : "https://ltnhotin.github.io"  # URL trang web
logo                     : "/assets/images/favicon.png"  # Đường dẫn đến logo
masthead_title           : "Nho's Journey"  # Tiêu đề của tiêu đề trang web
words_per_minute         : 200  # Số từ trung bình mỗi phút

# Tác giả
author:
  name             : "Lê Tô Nho Tín"  # Tên tác giả
  avatar           : "/assets/images/avatar.jpg"  # Đường dẫn đến ảnh đại diện
  bio              : "I'm a **AI Engineering** Student at FPTU-HCM&QN"  # Tiểu sử
  location         : "Viet Nam"  # Địa chỉ

# Chân trang
footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/tin.letonho"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LTNhoTin"

# Các tùy chọn cài đặt khác và xử lý
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  # Loại bỏ các thư mục không cần thiết
keep_files:
  - .git
  - .svn
encoding: "utf-8"  # Mã hóa UTF-8

markdown: kramdown  # Cài đặt sử dụng Kramdown
highlighter: rouge  # Cài đặt sử dụng Rouge cho việc tô màu cú pháp
paginate: 5  # Số bài viết trên mỗi trang
