minimal_mistakes_skin    : "dark"

locale                   : "en-US"
title                    : "Nho Tin | Personal Blog"
subtitle                 : "My Personal Blog"
name                     : "Lê Tô Nho Tín"
description              : "Blog about Knowledge sharing in programming and My personal life as a programmer"
url                      : "https://ltnhotin.github.io"
logo                     : "/assets/images/favicon.png"
masthead_title           : "Nho's Journey"
words_per_minute         : 200

author:
  name             : "Lê Tô Nho Tín"
  avatar           : "/assets/images/avatar.jpg"
  bio              : "I'm a **AI Engineering** Student at FPTU-HCM&QN"
  location         : "Viet Nam"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "https://mail.google.com/mail/?view=cm&fs=1&to=nhotin911@gmail.com"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/tin.letonho"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LTNhoTin"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/tin.letonho"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LTNhoTin"

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
